### ISSUE TITLE
Permission denied to access property "arguments"

### ISSUE THREAD

**Issue by boyomarinov** [firebug/firebug#7950] opened 2015-10-01 07:42 UTC
The error is as follows: 

     Error: Permission denied to access property "arguments"
     if (e['arguments'] && e.stack) {
     stacktrace.js (line 71, col 1)

It is thrown by the [Stacktrace library](https://github.com/stacktracejs/stacktrace.js/), but only when Firebug is enabled, otherwise it doesn't show up the error. Breaks in Firefox 41, but works fine in older versions of FF.

 - OS: Windows 7
 - Firebug version: 2.0.12

**Comment by fflorent** [comment] 2015-10-01 11:47
Does it show up exceptions when using the DevTools

**Comment by boyomarinov** [comment] 2015-10-01 14:21
With Firebug enabled, it shows the exception in both DevTools and Firebug. When disabled, message is not shown in DevTools.

**Comment by simonlindholm** [comment] 2015-10-01 14:24
I get the vague feeling that 1) Firebug is throwing an exception from console.error or similar, which it should not, 2) that exception is chrome-created, so causes these errors.

**Comment by fflorent** [comment] 2015-10-08 11:25
Maybe related to issue #7948. Can you give this [try-build](https://github.com/firebug/firebug/issues/7948#issuecomment-145633240) a try and tell us if it works?

Florent

**Comment by boyomarinov** [comment] 2015-10-09 08:33
Hei, Florent. I tested with the version you mentioned and it looks good. The error is gone from firebug as well as from the dev tools.

**Comment by fflorent** [comment] 2015-10-10 06:59
Thank you for the feedback ! FYI, the release with the fix will happen soon.

Florent

**Comment by fflorent** [comment] 2015-10-10 07:00
Duplicate of #7948

**Closed by fflorent** 2015-10-10 07:00 UTC
