### ISSUE TITLE
No Javascript on this page

### ISSUE THREAD

**Issue by sdavidg** [firebug/firebug#7925] opened 2015-07-23 09:13 UTC
On this page:
1) open firebug and enable script panel -> panel shows javascript files
2) close firebug
3) open firebug and go to script panel -> Script panel claims: 

No Javascript on this page
If \<script> tags have a "type" attribute, it should equal "text/javascript" or "application/javascript". Also scripts must be parsable (syntactically correct).

FF 39.0
Fb 2.0.11
David

**Comment by SebastianZ** [comment] 2015-07-23 11:51
That's a duplicate of issue #7918.

Sebastian

**Closed by SebastianZ** 2015-07-23 11:51 UTC

**Comment by rico042002** [comment] 2016-11-18 05:15
Ive actually had this problem today! I opened and closed firebug now it says that every page that I have ever created does not have a script in it. It's really starting to bum me out

**Comment by nsssim** [comment] 2016-11-22 07:21
I confirm, this is a new issue  now I have "If <script> tags have a "type" attribute, it should equal "text/javascript" or "application/javascript". Also scripts must be parsable (syntactically correct)." on every script
