### ISSUE TITLE
The functions executed from the command line shows internal errors

### ISSUE THREAD

**Issue by sdavidg** [firebug/firebug#7923] opened 2015-07-20 07:20 UTC
1) create a file:
```html
<html>
<head>
<title>The functions executed from the command line shows internal errors</title>
<script>
function x(){
	var a = "";
	console.log(a.a.a.a.a);
}
</script>		
</head>
<body>
<a href="javascript:x()">Click me!</a>
</body>
</html>
```

2) Enable Script panel 
3) Switch to Console panel

Case 1:
	1) click on "Click me!"
	2) The console panel claims "TypeError: a.a is undefined" -> OK
Case 2:
	1) Open the Command Editor and type: "x()"
	2) Hit "Enter
	3) The console panel claims:
		Error: Permission denied to access property "\__defineGetter__"
		chrome://firebug/content/console/commandLineExposed.js (línea 492, col 12)
	
FF 39.0
Fb 2.0.11

David

**Comment by fflorent** [comment] 2015-07-21 11:42
Thanks for the report David!

Indeed, I can reproduce this issue. That's something we have to fix.

Florent

2015-07-20 9:20 GMT+02:00 David <notifications@github.com>:

**Comment by fflorent** [comment] 2015-08-05 19:05
@janodvarko the commit above (https://github.com/firebug/firebug/commit/4ee34930d635cc4cc4080e4d9824ab9d6cfb4e16) fixes the issue for some reasons (is that an issue with the compartments?). But I am not really sure it is safe. Do you mind reviewing?

Florent

**Comment by simonlindholm** [comment] 2015-08-05 19:54
The issue here seems to be that https://bugzilla.mozilla.org/show_bug.cgi?id=837630 added `__proto__` to `Object.getOwnPropertyNames(Object.prototype)`, and thus the error modification loop changes the prototype of the newly created privileged Error object to some random unprivileged object, and weird things start to happen. So a more proper fix would be to add
```
if (prop === "__proto__")
    return;
```
to the forEach loop, or something in that vein.

**Comment by fflorent** [comment] 2015-08-05 20:06
Haha, very well done! Yes, that's seems to be that :). Thanks a lot, the patch is updated.

@janodvarko Should I merge it into master?

Florent

**Comment by janodvarko** [comment] 2015-08-06 08:09
Nice catch, yes please merge.

@fflorent Do you see any other blockers?
Can I go ahead and upload 2.0.12 for review?

Honza

**Comment by fflorent** [comment] 2015-08-06 10:04
Merged. 

>  Can I go ahead and upload 2.0.12 for review?

Sebastian has raised another issue, this time with Firefox 41 in the last comment of issue 7918 (https://github.com/firebug/firebug/issues/7918#issuecomment-128294580 ). I would say it is worth to include a fix for this.

Florent

**Closed by fflorent** 2015-08-06 10:04 UTC
Labels: 2.0.9, console, Test-case-available
