### ISSUE TITLE
Script execution stops at console.error with Script Panel enabled

### ISSUE THREAD

**Issue by gmircea** [firebug/firebug#7949] opened 2015-09-30 07:20 UTC
OS: Arch Linux 
Firefox 41.0
Firebug 2.0.12

If the Script Panel is enabled, when an console.error() is encountered in a javascript file, the code after that line is not executed anymore.
By disabling the Script Panel, or disabling Firebug altogether, the problem goes away.
I wrote a small jsfiddle test: https://jsfiddle.net/L2xacvq9/3/
Run the fiddle with the Script panel enabled and you'll see the following code in the console:
```
numbers: 1  2
```
Disable the Script panel and run the code again, you'll see the following code in the console:
```    
numbers: 1  2
incrementing
numbers: 10  20
```

**Comment by fflorent** [comment] 2015-10-01 11:50
Thanks for the report and the test case!

That sounds like a duplicate of bug #7948

Florent

**Closed by fflorent** 2015-10-01 11:50 UTC
