### ISSUE TITLE
"本页面不包含 JavaScript" 的问题

### ISSUE THREAD

**Issue by asmodai1985** [firebug/firebug#7927] opened 2015-07-30 01:16 UTC
场景：
F12   >>  切换至脚本：此时正常    >>  点击右侧关闭按钮  >> 再F12 >>提示:本页面不包含 JavaScript
如果我使用 F12 来关闭窗口则不会发生此bug.

English translation:
"Scenes:
F12 >> switch to the script: Now right click on the Close button OK >> >> again F12 >> Note: This page does not contain JavaScript
If I use F12 to close the window will not happen this bug"

**Comment by SebastianZ** [comment] 2015-08-03 07:43
Sounds like a duplicate of bug #7918.

Sebastian

**Closed by SebastianZ** 2015-08-03 07:43 UTC
