### ISSUE TITLE
Computed Side Panel appears to be broken.

### ISSUE THREAD

**Issue by dancoding** [firebug/firebug#8024] opened 2016-05-12 20:29 UTC
Today the [Computed Side Panel]([url]https://getfirebug.com/wiki/index.php/Computed_Side_Panel(url)) is suddenly not working as it normally does. All the properties are lumped together into the "Other" category. There are no plus/minus buttons to expand content. There are no links to style sheets. It's pretty much non-functional. I tried disabling all other add-ons, and that didn't help.

![screenshot-firebug-computed-styles png](https://cloud.githubusercontent.com/assets/6363534/15229318/b363378c-184d-11e6-9836-972b1c372009.jpg)

**Comment by gnysek** [comment] 2016-05-13 14:39
For me it also happens, after installing Firefox 46.0.1. Installing Firebug 2.0.15 didn't helped, so I assume this is something in latest Firefox update.

**Comment by SebastianZ** [comment] 2016-05-13 20:15
That's a duplicate of #8018.

Sebastian

**Closed by SebastianZ** 2016-05-13 20:15 UTC

**Comment by dancoding** [comment] 2016-05-13 22:14
Thanks so much, Sebastian!
I tried to comment on #8018, but my first attempt to comment failed. I think my second attempt was successful.

Dan

**Comment by SebastianZ** [comment] 2016-05-14 16:50
You're welcome, @dancoding!

Sebastian
